// Static registry of which pages/fields are CMS-editable. Keeps the page_content
// key-value table safe without DB-level schema enforcement: an unknown field_key is
// rejected at the Server Action layer rather than silently corrupting data.

export const CONTENT_PAGES = {
  home: {
    label: "Accueil",
    path: "/",
    fields: [
      "heroTitle",
      "heroSubtitle",
      "riveEyebrow",
      "riveTitle",
      "riveLead",
      "riveDeTitle",
      "riveDeBody",
      "riveAfTitle",
      "riveAfBody",
      "bridgeLine",
      "processEyebrow",
      "processTitle",
      "processLead",
      "acc1Title",
      "acc1Body",
      "acc2Title",
      "acc2Body",
      "acc3Title",
      "acc3Body",
      "acc4Title",
      "acc4Body",
      "acc5Title",
      "acc5Body",
      "acc6Title",
      "acc6Body",
      "acc7Title",
      "acc7Body",
      "categoriesTitle",
      "categoriesSubtitle",
      "categoriesCta",
      "finalCtaTitle",
      "finalCtaSubtitle",
    ],
  },
  aPropos: {
    label: "À propos",
    path: "/a-propos",
    fields: [
      "title",
      "intro",
      "missionTitle",
      "missionBody",
      "founderTitle",
      "founderBody",
      "valuesTitle",
      "value1",
      "value2",
      "value3",
      "distingueEyebrow",
      "distingueTitle",
      "distingueLead",
      "dist1Title",
      "dist1Body",
      "dist2Title",
      "dist2Body",
      "dist3Title",
      "dist3Body",
      "dist4Title",
      "dist4Body",
      "ethiqueEyebrow",
      "ethiqueTitle",
      "ethiqueHeading",
      "ethiqueBody1",
      "ethiqueBody2",
      "ethiqueNote",
      "equipeEyebrow",
      "equipeTitle",
      "equipeLead",
      "equipeNote",
      "faqEyebrow",
      "faqTitle",
      "doorsTitle",
      "doorsText",
      "doorsCandidat",
      "doorsEntreprise",
    ],
  },
  aProposHistoire: {
    label: "À propos : Notre histoire",
    path: "/a-propos/notre-histoire",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  aProposMethode: {
    label: "À propos : Notre méthode",
    path: "/a-propos/methode",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
      "section4Title",
      "section4Body",
    ],
  },
  candidats: {
    label: "Candidats : Accueil",
    path: "/candidats",
    fields: [
      "title",
      "subtitle",
      "kick",
      "ctaEligibility",
      "ctaVoies",
      "voiesEyebrow",
      "voiesTitle",
      "voiesLead",
      "voie1Title",
      "voie1Sub",
      "voie1Body",
      "voie2Flag",
      "voie2Title",
      "voie2Sub",
      "voie2Body",
      "voie3Title",
      "voie3Sub",
      "voie3Body",
      "tableNote",
      "eligibiliteEyebrow",
      "eligibiliteTitle",
      "eligibiliteLead",
      "crit1Title",
      "crit1Body",
      "crit2Title",
      "crit2Body",
      "crit3Title",
      "crit3Body",
      "crit4Title",
      "crit4Body",
      "ctaEval",
      "accompagnementEyebrow",
      "accompagnementTitle",
      "accompagnementLead",
      "acc1Title",
      "acc1Body",
      "acc2Title",
      "acc2Body",
      "acc3Title",
      "acc3Body",
      "acc4Title",
      "acc4Body",
      "acc5Title",
      "acc5Body",
      "acc6Title",
      "acc6Body",
      "acc7Title",
      "acc7Body",
      "formationsEyebrow",
      "formationsTitle",
      "formationsLead",
      "blogEyebrow",
      "blogTitle",
      "blogLead",
      "faqEyebrow",
      "faqTitle",
      "finalTitle",
      "finalText",
      "finalCta",
    ],
  },
  candidatsDiplomes: {
    label: "Candidats : Reconnaissance des diplômes",
    path: "/candidats/reconnaissance-diplomes",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  candidatsVivre: {
    label: "Candidats : Vivre en Allemagne",
    path: "/candidats/vivre-en-allemagne",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  formations: {
    label: "Formations (section de la page Candidats)",
    path: "/candidats",
    fields: [
      "title",
      "subtitle",
      "fastTrack.title",
      "fastTrack.body",
      "fullTraining.title",
      "fullTraining.body",
      "fullTraining.levelsTitle",
      "fullTraining.levelA1",
      "fullTraining.levelA2",
      "fullTraining.levelB1",
      "fullTraining.levelB2",
      "fullTraining.levelPrep",
      "fullTraining.examsTitle",
      "fullTraining.examsBody",
      "fullTraining.includesTitle",
      "fullTraining.includes1",
      "fullTraining.includes2",
      "fullTraining.includes3",
      "fullTraining.includes4",
      "fullTraining.includes5",
      "pricingNote",
    ],
  },
  coursAllemand: {
    label: "Cours d'allemand (silo)",
    path: "/cours-allemand",
    fields: [
      "title",
      "subtitle",
      "kick",
      "ctaInscription",
      "ctaParcours",
      "forkEyebrow",
      "forkTitle",
      "forkLead",
      "fullCardBadge",
      "fullCardTitle",
      "fullCardBody",
      "fullCardCta",
      "fastCardBadge",
      "fastCardTitle",
      "fastCardBody",
      "fastCardCta",
      "pourquoiEyebrow",
      "pourquoiTitle",
      "pourquoiLead",
      "voie1Title",
      "voie1Body",
      "voie2Title",
      "voie2Body",
      "voie3Title",
      "voie3Body",
      "voiesNote",
      "parcoursEyebrow",
      "parcoursTitle",
      "parcoursLead",
      "a1Title",
      "a1Duree",
      "a1Body",
      "a2Title",
      "a2Duree",
      "a2Body",
      "b1Title",
      "b1Duree",
      "b1Body",
      "b2Title",
      "b2Duree",
      "b2Body",
      "prepTitle",
      "prepDuree",
      "prepBody",
      "totalNote",
      "metierEyebrow",
      "metierTitle",
      "metierBody1",
      "metierBody2",
      "examensEyebrow",
      "examensTitle",
      "examensLead",
      "examensCta",
      "inscriptionEyebrow",
      "inscriptionTitle",
      "inc1",
      "inc2",
      "inc3",
      "inc4",
      "inc5",
      "pricingNote",
      "fastEyebrow",
      "fastTitle",
      "fastLead",
      "fastInclTitle",
      "fastIncl1",
      "fastIncl2",
      "fastIncl3",
      "fastIncl4",
      "fastStepsTitle",
      "fastStep1Title",
      "fastStep1Body",
      "fastStep2Title",
      "fastStep2Body",
      "fastStep3Title",
      "fastStep3Body",
      "fastStep4Title",
      "fastStep4Body",
      "fastNote",
      "fastCta",
      "finalTitle",
      "finalText",
      "finalCta",
    ],
  },
  ausbildung: {
    label: "Ausbildung (silo)",
    path: "/ausbildung-allemagne",
    fields: [
      "title",
      "subtitle",
      "kick",
      "ctaEval",
      "ctaSalaire",
      "quoiEyebrow",
      "quoiTitle",
      "quoiLead",
      "quoi1Title",
      "quoi1Body",
      "quoi2Title",
      "quoi2Body",
      "quoi3Title",
      "quoi3Body",
      "conditionsEyebrow",
      "conditionsTitle",
      "conditionsLead",
      "cond1Title",
      "cond1Body",
      "cond2Title",
      "cond2Body",
      "cond3Title",
      "cond3Body",
      "cond4Title",
      "cond4Body",
      "conditionsNote",
      "conditionsCta",
      "langueEyebrow",
      "langueTitle",
      "langueBody1",
      "langueBody2",
      "langueCta",
      "salaireEyebrow",
      "salaireTitle",
      "salaireLead",
      "salaireCta",
      "etapesEyebrow",
      "etapesTitle",
      "etape1Title",
      "etape1Body",
      "etape2Title",
      "etape2Body",
      "etape3Title",
      "etape3Body",
      "etape4Title",
      "etape4Body",
      "etape5Title",
      "etape5Body",
      "apresEyebrow",
      "apresTitle",
      "apresBody1",
      "apresBody2",
      "finalTitle",
      "finalText",
      "finalCta",
      "employeurNote",
      "employeurCta",
    ],
  },
  ausbildungSalaire: {
    // The euro figures are public German data (BIBB/BBiG) and go stale every year --
    // they're editable so they can be refreshed without a deploy. Whoever updates them
    // must also update minNote/moyNote, which carry the source and the reference date.
    label: "Ausbildung : Salaire",
    path: "/ausbildung-allemagne/salaire",
    fields: [
      "title",
      "subtitle",
      "kick",
      "minEyebrow",
      "minTitle",
      "minLead",
      "minY1",
      "minY2",
      "minY3",
      "minY4",
      "minV1",
      "minV2",
      "minV3",
      "minV4",
      "minNote",
      "moyEyebrow",
      "moyTitle",
      "moyLead",
      "moy1Label",
      "moy1Value",
      "moy2Label",
      "moy2Value",
      "moy3Label",
      "moy3Value",
      "moyBody",
      "moyNote",
      "varieEyebrow",
      "varieTitle",
      "varie1Title",
      "varie1Body",
      "varie2Title",
      "varie2Body",
      "varie3Title",
      "varie3Body",
      "varie4Title",
      "varie4Body",
      "disclaimer",
      "finalTitle",
      "finalText",
      "finalCta",
    ],
  },
  visa: {
    label: "Visa (silo)",
    path: "/visa-allemagne",
    fields: [
      "title",
      "subtitle",
      "kick",
      "ctaEval",
      "ctaTypes",
      "introEyebrow",
      "introTitle",
      "introLead",
      "typesEyebrow",
      "typesTitle",
      "typesLead",
      "type1Title",
      "type1Ref",
      "type1Body",
      "type1Cta",
      "type2Title",
      "type2Ref",
      "type2Body",
      "type2Cta",
      "type3Title",
      "type3Ref",
      "type3Body",
      "type3Cta",
      "roleEyebrow",
      "roleTitle",
      "roleLead",
      "role1Title",
      "role1Body",
      "role2Title",
      "role2Body",
      "role3Title",
      "role3Body",
      "role4Title",
      "role4Body",
      "delaisEyebrow",
      "delaisTitle",
      "delaisBody",
      "finalTitle",
      "finalText",
      "finalCta",
    ],
  },
  visaChancenkarte: {
    // The point values come from § 20a AufenthG (public German law). Editable so they can
    // be refreshed if the schedule changes; whoever edits them must also update
    // pointsNote, which carries the source and the in-force date.
    label: "Visa : Chancenkarte",
    path: "/visa-allemagne/chancenkarte",
    fields: [
      "title",
      "subtitle",
      "kick",
      "quoiEyebrow",
      "quoiTitle",
      "quoiLead",
      "quoi1Title",
      "quoi1Body",
      "quoi2Title",
      "quoi2Body",
      "quoi3Title",
      "quoi3Body",
      "baseEyebrow",
      "baseTitle",
      "baseLead",
      "base1Title",
      "base1Body",
      "base2Title",
      "base2Body",
      "base3Title",
      "base3Body",
      "pointsEyebrow",
      "pointsTitle",
      "pointsLead",
      "pointsCol1",
      "pointsCol2",
      "p1Label",
      "p1Val",
      "p2Label",
      "p2Val",
      "p3Label",
      "p3Val",
      "p4Label",
      "p4Val",
      "p5Label",
      "p5Val",
      "p6Label",
      "p6Val",
      "p7Label",
      "p7Val",
      "p8Label",
      "p8Val",
      "p9Label",
      "p9Val",
      "p10Label",
      "p10Val",
      "p11Label",
      "p11Val",
      "p12Label",
      "p12Val",
      "pointsNote",
      "roleEyebrow",
      "roleTitle",
      "roleBody",
      "roleCta",
      "disclaimer",
      "finalTitle",
      "finalText",
      "finalCta",
    ],
  },
  travailler: {
    label: "Travailler en Allemagne (silo)",
    path: "/travailler-en-allemagne",
    fields: [
      "title",
      "subtitle",
      "kick",
      "ctaEval",
      "ctaMetiers",
      "contexteEyebrow",
      "contexteTitle",
      "contexteLead",
      "contexteBody",
      "exploreEyebrow",
      "exploreTitle",
      "card1Title",
      "card1Body",
      "card1Cta",
      "card2Title",
      "card2Body",
      "card2Cta",
      "card3Title",
      "card3Body",
      "card3Cta",
      "cadreEyebrow",
      "cadreTitle",
      "cadreBody1",
      "cadreBody2",
      "finalTitle",
      "finalText",
      "finalCta",
    ],
  },
  travaillerSalaires: {
    // Entgeltatlas medians (public German data) that go stale yearly -- editable so they
    // can be refreshed without a deploy. Whoever updates a value must also update
    // tableNote, which carries the source and the reference year.
    label: "Travailler en Allemagne : Salaires",
    path: "/travailler-en-allemagne/salaires",
    fields: [
      "title",
      "subtitle",
      "kick",
      "repereEyebrow",
      "repereTitle",
      "repereLead",
      "tableEyebrow",
      "tableTitle",
      "tableLead",
      "tableCol1",
      "tableCol2",
      "r1Label",
      "r1Val",
      "r2Label",
      "r2Val",
      "r3Label",
      "r3Val",
      "r4Label",
      "r4Val",
      "r5Label",
      "r5Val",
      "tableNote",
      "varieEyebrow",
      "varieTitle",
      "varie1Title",
      "varie1Body",
      "varie2Title",
      "varie2Body",
      "varie3Title",
      "varie3Body",
      "varie4Title",
      "varie4Body",
      "disclaimer",
      "finalTitle",
      "finalText",
      "finalCta",
    ],
  },
  partir: {
    label: "Partir en Allemagne (silo)",
    path: "/partir-en-allemagne",
    fields: [
      "title",
      "subtitle",
      "kick",
      "ctaEval",
      "ctaCameroun",
      "ancrageEyebrow",
      "ancrageTitle",
      "ancrageBody1",
      "ancrageBody2",
      "paysEyebrow",
      "paysTitle",
      "paysLead",
      "camerounCardTitle",
      "camerounCardBadge",
      "camerounCardBody",
      "camerounCardCta",
      "autresTitle",
      "autresBody",
      "autresCta",
      "finalTitle",
      "finalText",
      "finalCta",
    ],
  },
  partirCameroun: {
    // The visa facts (Yaoundé embassy, VFS Global route) are web-verified public info,
    // dated in visaNote. Editable so the note can be refreshed as the procedure changes.
    label: "Partir en Allemagne : Cameroun",
    path: "/partir-en-allemagne/cameroun",
    fields: [
      "title",
      "subtitle",
      "kick",
      "ctaEval",
      "avantageEyebrow",
      "avantageTitle",
      "avantageBody1",
      "avantageBody2",
      "parcoursEyebrow",
      "parcoursTitle",
      "etape1Title",
      "etape1Body",
      "etape2Title",
      "etape2Body",
      "etape3Title",
      "etape3Body",
      "etape4Title",
      "etape4Body",
      "visaEyebrow",
      "visaTitle",
      "visaBody1",
      "visaBody2",
      "visaNote",
      "roleEyebrow",
      "roleTitle",
      "role1",
      "role2",
      "role3",
      "role4",
      "role5",
      "finalTitle",
      "finalText",
      "finalCta",
      "contactNote",
      "contactCta",
    ],
  },
  formationsExamens: {
    label: "Cours d'allemand : Préparation examens",
    path: "/cours-allemand/preparation-examens",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  formationsIntegration: {
    label: "Formations : Mise à niveau & intégration",
    path: "/candidats/formations/integration",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  entreprises: {
    label: "Entreprises : Accueil",
    path: "/entreprises",
    fields: [
      "title",
      "subtitle",
      "kick",
      "ctaContact",
      "ctaProcessus",
      "probEyebrow",
      "probTitle",
      "probBody1",
      "probBody2",
      "pourquoiEyebrow",
      "pourquoiTitle",
      "pourquoiLead",
      "pil1Title",
      "pil1Body",
      "pil2Title",
      "pil2Body",
      "pil3Title",
      "pil3Body",
      "secteursEyebrow",
      "secteursTitle",
      "secteursLead",
      "seg1Title",
      "seg1Body",
      "seg2Title",
      "seg2Body",
      "seg3Title",
      "seg3Body",
      "seg4Title",
      "seg4Body",
      "servicesEyebrow",
      "servicesTitle",
      "servicesLead",
      "srv1Title",
      "srv1Body",
      "srv2Title",
      "srv2Body",
      "srv3Title",
      "srv3Body",
      "srv4Title",
      "srv4Body",
      "profilsEyebrow",
      "profilsTitle",
      "profilsLead",
      "profilsCta",
      "besoinsEyebrow",
      "besoinsTitle",
      "besoinsLead",
      "besoin1Badge",
      "besoin1Title",
      "besoin1Body",
      "besoin2Badge",
      "besoin2Title",
      "besoin2Body",
      "pourquoiAfriqueEyebrow",
      "pourquoiAfriqueTitle",
      "pourquoiAfriqueBody1",
      "pourquoiAfriqueBody2",
      "pourquoiAfriqueCta",
      "modelesEyebrow",
      "modelesTitle",
      "modelesLead",
      "modele1Badge",
      "modele1Title",
      "modele1Body",
      "modele2Badge",
      "modele2Title",
      "modele2Body",
      "processusEyebrow",
      "processusTitle",
      "processusLead",
      "proc1Title",
      "proc1Body",
      "proc2Title",
      "proc2Body",
      "proc3Title",
      "proc3Body",
      "proc4Title",
      "proc4Body",
      "proc5Title",
      "proc5Body",
      "proc6Title",
      "proc6Body",
      "proc7Title",
      "proc7Body",
      "cadreEyebrow",
      "cadreTitle",
      "cadreLead",
      "cadre1Title",
      "cadre1Body",
      "cadre2Title",
      "cadre2Body",
      "cadre3Title",
      "cadre3Body",
      "cadreNote",
      "rolesEyebrow",
      "rolesTitle",
      "rolesLead",
      "rolesUsTitle",
      "rolesYouTitle",
      "garantiesEyebrow",
      "garantiesTitle",
      "garantiesLead",
      "gar1Title",
      "gar1Body",
      "gar2Title",
      "gar2Body",
      "gar3Title",
      "gar3Body",
      "gar4Title",
      "gar4Body",
      "gar5Title",
      "gar5Body",
      "gar6Title",
      "gar6Body",
      "partenaireEyebrow",
      "partenaireTitle",
      "partenaireLead",
      "partenaireCta",
      "faqEyebrow",
      "faqTitle",
      "contactEyebrow",
      "contactTitle",
      "contactLead",
      "contactCta",
      "contactCtaSecondary",
    ],
  },
  entreprisesPartenariat: {
    label: "Entreprises : Devenir partenaire",
    path: "/entreprises/partenariat",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  partenaires: {
    label: "Partenaires",
    path: "/partenaires",
    fields: ["title", "subtitle", "growingBody"],
  },
  temoignages: {
    label: "Témoignages",
    path: "/temoignages",
    fields: ["title", "subtitle", "placeholder"],
  },
  postuler: {
    label: "Postuler",
    path: "/postuler",
    fields: ["title", "subtitle", "body"],
  },
  cgu: {
    label: "CGU",
    path: "/cgu",
    fields: [
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  contact: {
    label: "Contact",
    path: "/contact",
    fields: ["title", "subtitle", "office", "officeLocation"],
  },
  metiers: {
    label: "Métiers qui recrutent",
    path: "/metiers",
    fields: [
      "title",
      "subtitle",
      "kick",
      "ctaEligibility",
      "ctaSecteurs",
      "contexteEyebrow",
      "contexteTitle",
      "contexteLead",
      "contexteBody",
      "secteursEyebrow",
      "secteursTitle",
      "secteursLead",
      "eligibiliteEyebrow",
      "eligibiliteTitle",
      "eligibiliteLead",
      "crit1Title",
      "crit1Body",
      "crit2Title",
      "crit2Body",
      "crit3Title",
      "crit3Body",
      "crit4Title",
      "crit4Body",
      "parcoursEyebrow",
      "parcoursTitle",
      "step1Title",
      "step1Body",
      "step2Title",
      "step2Body",
      "step3Title",
      "step3Body",
      "step4Title",
      "step4Body",
      "faqEyebrow",
      "faqTitle",
      "finalTitle",
      "finalText",
      "finalCta",
    ],
  },
} as const;

export type ContentPageKey = keyof typeof CONTENT_PAGES;

export function isValidContentField(pageKey: string, fieldKey: string): boolean {
  const page = CONTENT_PAGES[pageKey as ContentPageKey];
  if (!page) return false;
  return (page.fields as readonly string[]).includes(fieldKey);
}

export const IMAGE_SLOTS = {
  site_logo: { label: "Logo du site" },
} as const;

export type ImageSlotKey = keyof typeof IMAGE_SLOTS;
