// Static registry of which pages/fields are CMS-editable. Keeps the page_content
// key-value table safe without DB-level schema enforcement: an unknown field_key is
// rejected at the Server Action layer rather than silently corrupting data.

export const CONTENT_PAGES = {
  home: {
    label: "Accueil",
    path: "/",
    fields: [
      "heroTitle",
      "heroSubtitle",
      "whyTitle",
      "why1Title",
      "why1Body",
      "why2Title",
      "why2Body",
      "why3Title",
      "why3Body",
      "tracksTitle",
      "fastTrackTitle",
      "fastTrackBody",
      "fullTrainingTitle",
      "fullTrainingBody",
      "categoriesTitle",
      "categoriesSubtitle",
      "categoriesCta",
      "finalCtaTitle",
      "finalCtaSubtitle",
    ],
  },
  aPropos: {
    label: "À propos",
    path: "/a-propos",
    fields: [
      "title",
      "intro",
      "missionTitle",
      "missionBody",
      "founderTitle",
      "founderBody",
      "valuesTitle",
      "value1",
      "value2",
      "value3",
    ],
  },
  aProposHistoire: {
    label: "À propos : Notre histoire",
    path: "/a-propos/notre-histoire",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  aProposMethode: {
    label: "À propos : Notre méthode",
    path: "/a-propos/methode",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
      "section4Title",
      "section4Body",
    ],
  },
  candidats: {
    label: "Candidats : Accueil",
    path: "/candidats",
    fields: [
      "title",
      "subtitle",
      "step1Title",
      "step1Body",
      "step2Title",
      "step2Body",
      "step3Title",
      "step3Body",
      "step4Title",
      "step4Body",
    ],
  },
  candidatsComment: {
    label: "Candidats : Comment ça marche",
    path: "/candidats/comment-ca-marche",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
      "section4Title",
      "section4Body",
    ],
  },
  candidatsEligibilite: {
    label: "Candidats : Suis-je éligible ?",
    path: "/candidats/eligibilite",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
      "section4Title",
      "section4Body",
    ],
  },
  candidatsDiplomes: {
    label: "Candidats : Reconnaissance des diplômes",
    path: "/candidats/reconnaissance-diplomes",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  candidatsVivre: {
    label: "Candidats : Vivre en Allemagne",
    path: "/candidats/vivre-en-allemagne",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  candidatsFaq: {
    label: "Candidats : FAQ",
    path: "/candidats/faq",
    fields: ["title", "subtitle"],
  },
  formations: {
    label: "Formations : Accueil",
    path: "/candidats/formations",
    fields: [
      "title",
      "subtitle",
      "fastTrack.title",
      "fastTrack.body",
      "fullTraining.title",
      "fullTraining.body",
      "fullTraining.levelsTitle",
      "fullTraining.levelA1",
      "fullTraining.levelA2",
      "fullTraining.levelB1",
      "fullTraining.levelB2",
      "fullTraining.levelPrep",
      "fullTraining.examsTitle",
      "fullTraining.examsBody",
      "fullTraining.includesTitle",
      "fullTraining.includes1",
      "fullTraining.includes2",
      "fullTraining.includes3",
      "fullTraining.includes4",
      "fullTraining.includes5",
      "pricingNote",
    ],
  },
  formationsAllemand: {
    label: "Formations : Cours d'allemand",
    path: "/candidats/formations/allemand",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  formationsExamens: {
    label: "Formations : Préparation examens",
    path: "/candidats/formations/examens",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  formationsIntegration: {
    label: "Formations : Mise à niveau & intégration",
    path: "/candidats/formations/integration",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  entreprises: {
    label: "Entreprises : Accueil",
    path: "/entreprises",
    fields: [
      "title",
      "subtitle",
      "step1Title",
      "step1Body",
      "step2Title",
      "step2Body",
      "step3Title",
      "step3Body",
      "step4Title",
      "step4Body",
    ],
  },
  entreprisesServices: {
    label: "Entreprises : Nos services",
    path: "/entreprises/services",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  entreprisesProfils: {
    label: "Entreprises : Profils & secteurs",
    path: "/entreprises/profils",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  entreprisesPartenariat: {
    label: "Entreprises : Devenir partenaire",
    path: "/entreprises/partenariat",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  entreprisesProcessus: {
    label: "Entreprises : Notre processus",
    path: "/entreprises/processus",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  entreprisesPourquoi: {
    label: "Entreprises : Pourquoi l'Afrique centrale",
    path: "/entreprises/pourquoi-afrique-centrale",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  entreprisesDemande: {
    label: "Entreprises : Demande de main-d'œuvre",
    path: "/entreprises/demande",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  partenaires: {
    label: "Partenaires",
    path: "/partenaires",
    fields: ["title", "subtitle", "growingBody"],
  },
  temoignages: {
    label: "Témoignages",
    path: "/temoignages",
    fields: ["title", "subtitle", "placeholder"],
  },
  postuler: {
    label: "Postuler",
    path: "/postuler",
    fields: ["title", "subtitle", "body"],
  },
  cgu: {
    label: "CGU",
    path: "/cgu",
    fields: [
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  contact: {
    label: "Contact",
    path: "/contact",
    fields: ["title", "subtitle", "office", "officeLocation"],
  },
  metiers: {
    label: "Métiers en pénurie (intro)",
    path: "/candidats/metiers",
    fields: ["title", "subtitle"],
  },
} as const;

export type ContentPageKey = keyof typeof CONTENT_PAGES;

export function isValidContentField(pageKey: string, fieldKey: string): boolean {
  const page = CONTENT_PAGES[pageKey as ContentPageKey];
  if (!page) return false;
  return (page.fields as readonly string[]).includes(fieldKey);
}

export const IMAGE_SLOTS = {
  site_logo: { label: "Logo du site" },
} as const;

export type ImageSlotKey = keyof typeof IMAGE_SLOTS;
