// Static registry of which pages/fields are CMS-editable. Keeps the page_content
// key-value table safe without DB-level schema enforcement: an unknown field_key is
// rejected at the Server Action layer rather than silently corrupting data.

export const CONTENT_PAGES = {
  home: {
    label: "Accueil",
    path: "/",
    fields: [
      "heroTitle",
      "heroSubtitle",
      "riveEyebrow",
      "riveTitle",
      "riveLead",
      "riveDeTitle",
      "riveDeBody",
      "riveAfTitle",
      "riveAfBody",
      "bridgeLine",
      "processEyebrow",
      "processTitle",
      "processLead",
      "proc1Title",
      "proc1Body",
      "proc2Title",
      "proc2Body",
      "proc3Title",
      "proc3Body",
      "proc4Title",
      "proc4Body",
      "whyTitle",
      "why1Title",
      "why1Body",
      "why2Title",
      "why2Body",
      "why3Title",
      "why3Body",
      "tracksTitle",
      "fastTrackTitle",
      "fastTrackBody",
      "fullTrainingTitle",
      "fullTrainingBody",
      "categoriesTitle",
      "categoriesSubtitle",
      "categoriesCta",
      "finalCtaTitle",
      "finalCtaSubtitle",
    ],
  },
  aPropos: {
    label: "À propos",
    path: "/a-propos",
    fields: [
      "title",
      "intro",
      "missionTitle",
      "missionBody",
      "founderTitle",
      "founderBody",
      "valuesTitle",
      "value1",
      "value2",
      "value3",
      "distingueEyebrow",
      "distingueTitle",
      "distingueLead",
      "dist1Title",
      "dist1Body",
      "dist2Title",
      "dist2Body",
      "dist3Title",
      "dist3Body",
      "dist4Title",
      "dist4Body",
      "ethiqueEyebrow",
      "ethiqueTitle",
      "ethiqueHeading",
      "ethiqueBody1",
      "ethiqueBody2",
      "ethiqueNote",
      "equipeEyebrow",
      "equipeTitle",
      "equipeLead",
      "equipeNote",
      "faqEyebrow",
      "faqTitle",
      "doorsTitle",
      "doorsText",
      "doorsCandidat",
      "doorsEntreprise",
    ],
  },
  aProposHistoire: {
    label: "À propos : Notre histoire",
    path: "/a-propos/notre-histoire",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  aProposMethode: {
    label: "À propos : Notre méthode",
    path: "/a-propos/methode",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
      "section4Title",
      "section4Body",
    ],
  },
  candidats: {
    label: "Candidats : Accueil",
    path: "/candidats",
    fields: [
      "title",
      "subtitle",
      "kick",
      "ctaEligibility",
      "ctaVoies",
      "voiesEyebrow",
      "voiesTitle",
      "voiesLead",
      "voie1Title",
      "voie1Sub",
      "voie1Body",
      "voie2Flag",
      "voie2Title",
      "voie2Sub",
      "voie2Body",
      "voie3Title",
      "voie3Sub",
      "voie3Body",
      "tableNote",
      "eligibiliteEyebrow",
      "eligibiliteTitle",
      "eligibiliteLead",
      "crit1Title",
      "crit1Body",
      "crit2Title",
      "crit2Body",
      "crit3Title",
      "crit3Body",
      "crit4Title",
      "crit4Body",
      "ctaEval",
      "accompagnementEyebrow",
      "accompagnementTitle",
      "accompagnementLead",
      "acc1Title",
      "acc1Body",
      "acc2Title",
      "acc2Body",
      "acc3Title",
      "acc3Body",
      "acc4Title",
      "acc4Body",
      "acc5Title",
      "acc5Body",
      "acc6Title",
      "acc6Body",
      "acc7Title",
      "acc7Body",
      "metiersEyebrow",
      "metiersTitle",
      "metiersLead",
      "metiersCta",
      "statBig",
      "statText",
      "formationsEyebrow",
      "formationsTitle",
      "formationsLead",
      "blogEyebrow",
      "blogTitle",
      "blogLead",
      "faqEyebrow",
      "faqTitle",
      "finalTitle",
      "finalText",
      "finalCta",
    ],
  },
  candidatsDiplomes: {
    label: "Candidats : Reconnaissance des diplômes",
    path: "/candidats/reconnaissance-diplomes",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  candidatsVivre: {
    label: "Candidats : Vivre en Allemagne",
    path: "/candidats/vivre-en-allemagne",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  formations: {
    label: "Formations (section de la page Candidats)",
    path: "/candidats",
    fields: [
      "title",
      "subtitle",
      "fastTrack.title",
      "fastTrack.body",
      "fullTraining.title",
      "fullTraining.body",
      "fullTraining.levelsTitle",
      "fullTraining.levelA1",
      "fullTraining.levelA2",
      "fullTraining.levelB1",
      "fullTraining.levelB2",
      "fullTraining.levelPrep",
      "fullTraining.examsTitle",
      "fullTraining.examsBody",
      "fullTraining.includesTitle",
      "fullTraining.includes1",
      "fullTraining.includes2",
      "fullTraining.includes3",
      "fullTraining.includes4",
      "fullTraining.includes5",
      "pricingNote",
    ],
  },
  formationsAllemand: {
    label: "Formations : Cours d'allemand",
    path: "/candidats/formations/allemand",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  formationsExamens: {
    label: "Formations : Préparation examens",
    path: "/candidats/formations/examens",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  formationsIntegration: {
    label: "Formations : Mise à niveau & intégration",
    path: "/candidats/formations/integration",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  entreprises: {
    label: "Entreprises : Accueil",
    path: "/entreprises",
    fields: [
      "title",
      "subtitle",
      "kick",
      "ctaContact",
      "ctaProcessus",
      "probEyebrow",
      "probTitle",
      "probBody1",
      "probBody2",
      "pourquoiEyebrow",
      "pourquoiTitle",
      "pourquoiLead",
      "pil1Title",
      "pil1Body",
      "pil2Title",
      "pil2Body",
      "pil3Title",
      "pil3Body",
      "secteursEyebrow",
      "secteursTitle",
      "secteursLead",
      "seg1Title",
      "seg1Body",
      "seg2Title",
      "seg2Body",
      "seg3Title",
      "seg3Body",
      "seg4Title",
      "seg4Body",
      "servicesEyebrow",
      "servicesTitle",
      "servicesLead",
      "srv1Title",
      "srv1Body",
      "srv2Title",
      "srv2Body",
      "srv3Title",
      "srv3Body",
      "srv4Title",
      "srv4Body",
      "profilsEyebrow",
      "profilsTitle",
      "profilsLead",
      "profilsCta",
      "pourquoiAfriqueEyebrow",
      "pourquoiAfriqueTitle",
      "pourquoiAfriqueBody1",
      "pourquoiAfriqueBody2",
      "pourquoiAfriqueCta",
      "modelesEyebrow",
      "modelesTitle",
      "modelesLead",
      "modele1Badge",
      "modele1Title",
      "modele1Body",
      "modele2Badge",
      "modele2Title",
      "modele2Body",
      "processusEyebrow",
      "processusTitle",
      "processusLead",
      "proc1Title",
      "proc1Body",
      "proc2Title",
      "proc2Body",
      "proc3Title",
      "proc3Body",
      "proc4Title",
      "proc4Body",
      "proc5Title",
      "proc5Body",
      "proc6Title",
      "proc6Body",
      "proc7Title",
      "proc7Body",
      "cadreEyebrow",
      "cadreTitle",
      "cadreLead",
      "cadre1Title",
      "cadre1Body",
      "cadre2Title",
      "cadre2Body",
      "cadre3Title",
      "cadre3Body",
      "cadreNote",
      "rolesEyebrow",
      "rolesTitle",
      "rolesLead",
      "rolesUsTitle",
      "rolesYouTitle",
      "garantiesEyebrow",
      "garantiesTitle",
      "garantiesLead",
      "gar1Title",
      "gar1Body",
      "gar2Title",
      "gar2Body",
      "gar3Title",
      "gar3Body",
      "gar4Title",
      "gar4Body",
      "gar5Title",
      "gar5Body",
      "gar6Title",
      "gar6Body",
      "partenaireEyebrow",
      "partenaireTitle",
      "partenaireLead",
      "partenaireCta",
      "faqEyebrow",
      "faqTitle",
      "contactEyebrow",
      "contactTitle",
      "contactLead",
      "contactCta",
      "contactCtaSecondary",
    ],
  },
  entreprisesPartenariat: {
    label: "Entreprises : Devenir partenaire",
    path: "/entreprises/partenariat",
    fields: [
      "title",
      "subtitle",
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  partenaires: {
    label: "Partenaires",
    path: "/partenaires",
    fields: ["title", "subtitle", "growingBody"],
  },
  temoignages: {
    label: "Témoignages",
    path: "/temoignages",
    fields: ["title", "subtitle", "placeholder"],
  },
  postuler: {
    label: "Postuler",
    path: "/postuler",
    fields: ["title", "subtitle", "body"],
  },
  cgu: {
    label: "CGU",
    path: "/cgu",
    fields: [
      "section1Title",
      "section1Body",
      "section2Title",
      "section2Body",
      "section3Title",
      "section3Body",
    ],
  },
  contact: {
    label: "Contact",
    path: "/contact",
    fields: ["title", "subtitle", "office", "officeLocation"],
  },
  metiers: {
    label: "Métiers qui recrutent",
    path: "/candidats/metiers",
    fields: [
      "title",
      "subtitle",
      "kick",
      "ctaEligibility",
      "ctaSecteurs",
      "contexteEyebrow",
      "contexteTitle",
      "contexteLead",
      "contexteBody",
      "secteursEyebrow",
      "secteursTitle",
      "secteursLead",
      "eligibiliteEyebrow",
      "eligibiliteTitle",
      "eligibiliteLead",
      "crit1Title",
      "crit1Body",
      "crit2Title",
      "crit2Body",
      "crit3Title",
      "crit3Body",
      "crit4Title",
      "crit4Body",
      "parcoursEyebrow",
      "parcoursTitle",
      "step1Title",
      "step1Body",
      "step2Title",
      "step2Body",
      "step3Title",
      "step3Body",
      "step4Title",
      "step4Body",
      "faqEyebrow",
      "faqTitle",
      "finalTitle",
      "finalText",
      "finalCta",
    ],
  },
} as const;

export type ContentPageKey = keyof typeof CONTENT_PAGES;

export function isValidContentField(pageKey: string, fieldKey: string): boolean {
  const page = CONTENT_PAGES[pageKey as ContentPageKey];
  if (!page) return false;
  return (page.fields as readonly string[]).includes(fieldKey);
}

export const IMAGE_SLOTS = {
  site_logo: { label: "Logo du site" },
} as const;

export type ImageSlotKey = keyof typeof IMAGE_SLOTS;
